### ISSUE TITLE
issue running the example with external postgres

### ISSUE THREAD

**Issue by halindraprakoso** [nhost/hasura-auth#136]
Hello,

1. I was trying the docker-compose-example.yaml --> it worked

2. then I changed hasura-auth's `HASURA_GRAPHQL_DATABASE_URL` to `postgres://postgres@host.docker.internal:5432/test` --> still worked

3. changed graphql-engine's to the same and I'm having this issue (I've run the initdb script):

```js
,"data":{"path":"$.args","error":"source with name \"default\" does not exist","code":"not-exists"}},"isAxiosError":true,"stack":"Error: Request failed with status code 400\n    at createError (/app/node_modules/.pnpm/axios@0.21.1/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/app/node_modules/.pnpm/axios@0.21.1/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/app/node_modules/.pnpm/axios@0.21.1/node_modules/axios/lib/adapters/http.js:260:11)\n    at IncomingMessage.emit (events.js:412:35)\n    at endReadableNT (internal/streams/readable.js:1334:12)\n    at processTicksAndRejections (internal/process/task_queues.js:82:21)","type":"Error","msg":"Request failed with status code 400"}
schootive-hasura-auth-hasura-auth-1     | (node:19) UnhandledPromiseRejectionWarning: Error: Error tracking table provider_requests
schootive-hasura-auth-hasura-auth-1     |     at trackTable (/app/dist/metadata.js:29:19)
schootive-hasura-auth-hasura-auth-1     |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
schootive-hasura-auth-hasura-auth-1     |     at async applyMetadata (/app/dist/metadata.js:127:5)
schootive-hasura-auth-hasura-auth-1     |     at async start (/app/dist/server.js:39:5)
schootive-hasura-auth-hasura-auth-1     | (Use `node --trace-warnings ...` to show where the warning was created)
schootive-hasura-auth-hasura-auth-1     | (node:19) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
schootive-hasura-auth-hasura-auth-1     | (node:19) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
schootive-hasura-auth-hasura-auth-1 exited with code 0
```

what could be the problem?

**Comment by halindraprakoso** [comment]
seems like only changing graphql-engine's `HASURA_GRAPHQL_DATABASE_URL` to `postgres://postgres@host.docker.internal:5432/test` already caused the error regardless of hasura-auth's config

**Comment by purplefish32** [comment]
I think the postgres database has to be called "default" in Hasura for it to work

**Comment by halindraprakoso** [comment]
that seems to be it. Additionally, I had to remove/rename an existing table called `user` to something else.
