### ISSUE TITLE
Project incompatible with pnpm 7.0.0 

### ISSUE THREAD

**Issue by L3K0V** [nhost/hasura-auth#155]
Hello 👋,

I'm trying to contribute to the project but unfortunately I cannot use `dev`, `build` and `build:docker` commands. 

**Edit: the issue appears when use `pnpm` version 7.0.0**
**Workaround: Install pnpm@6**

Whatever command I'm trying to execute I get:

```
❯ pnpm run build

> hasura-auth@0.7.1 build /Users/azlekov/Workspace/dodi/hasura-auth
> rimraf dist && tsc --project tsconfig.build.json && tsc-alias

src/routes/signin/providers/utils.ts:9:32 - error TS2307: Cannot find module 'passport-oauth2' or its corresponding type declarations.

9 import { VerifyCallback } from 'passport-oauth2';
                                 ~~~~~~~~~~~~~~~~~

types/passport-generic-oauth.d.ts:6:27 - error TS2307: Cannot find module 'passport-oauth2' or its corresponding type declarations.

6   import oauth2 = require('passport-oauth2')
                            ~~~~~~~~~~~~~~~~~


Found 2 errors.

 ELIFECYCLE  Command failed with exit code 2.
```

@plmercereau I saw you are most active here, so can you guide me what could be the issue?

**Comment by L3K0V** [comment]
It looks the issue is fixed using `pnpm install --shamefully-hoist`. Is this the right approach installing the dependencies for this project?

**Comment by L3K0V** [comment]
When trying to run `pnpm run dev` I get:

```
❯ pnpm run dev

> hasura-auth@0.7.1 dev /Users/azlekov/Workspace/dodi/hasura-auth
> run-p  dev:start codegen:watch


> hasura-auth@0.7.1 dev:start /Users/azlekov/Workspace/dodi/hasura-auth
> ts-node-dev -r tsconfig-paths/register --respawn --clear  --unhandled-rejections=strict src/start.ts


> hasura-auth@0.7.1 codegen:watch /Users/azlekov/Workspace/dodi/hasura-auth
> dotenv graphql-codegen --config codegen.yaml --watch

[INFO] 18:50:38 ts-node-dev ver. 1.1.8 (using ts-node ver. 9.1.1, typescript ver. 4.5.4)
(node:3962) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3962) ExperimentalWarning: buffer.Blob is an experimental feature. This feature could change at any time
  ✔ Parse configuration
  ❯ Generate outputs
    ❯ Generate src/utils/__generated__/graphql-request.ts
      ✔ Load GraphQL schemas
      ✔ Load GraphQL documents
      ✖ Generate
        →     at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/users.graphql:172:55


 Found 1 error

  ✖ src/utils/__generated__/graphql-request.ts
    AggregateError: GraphQL Document Validation failed with 40 errors;
      Error 0: GraphQLDocumentError: Unknown type "users".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/provider-requests.graphql:1:24

    Error 1: GraphQLDocumentError: Unknown type "authProviderRequests_insert_input".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/provider-requests.graphql:2:21

    Error 2: GraphQLDocumentError: Unknown type "uuid".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/provider-requests.graphql:10:37

    Error 3: GraphQLDocumentError: Unknown type "uuid".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/provider-requests.graphql:17:28

    Error 4: GraphQLDocumentError: Cannot query field "authProviderRequest" on type "query_root".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/provider-requests.graphql:18:3

    Error 5: GraphQLDocumentError: Unknown type "users".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/refresh-tokens.graphql:1:24

    Error 6: GraphQLDocumentError: Unknown type "authRefreshTokens_insert_input".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/refresh-tokens.graphql:1:44

    Error 7: GraphQLDocumentError: Unknown type "uuid".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/refresh-tokens.graphql:7:44

    Error 8: GraphQLDocumentError: Unknown type "uuid".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/refresh-tokens.graphql:14:43

    Error 9: GraphQLDocumentError: Unknown type "users".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/user-providers.graphql:1:24

    Error 10: GraphQLDocumentError: Cannot query field "authUserProviders" on type "query_root".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/user-providers.graphql:2:3

    Error 11: GraphQLDocumentError: Unknown type "uuid".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/user-providers.graphql:18:29

    Error 12: GraphQLDocumentError: Cannot query field "authUserProviders" on type "query_root".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/user-providers.graphql:19:3

    Error 13: GraphQLDocumentError: Unknown type "uuid".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/user-providers.graphql:31:8

    Error 14: GraphQLDocumentError: Unknown type "authUserProviders_set_input".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/user-providers.graphql:32:22

    Error 15: GraphQLDocumentError: Unknown type "users".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/user-roles.graphql:1:24

    Error 16: GraphQLDocumentError: Unknown type "authUserRoles_insert_input".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/user-roles.graphql:1:39

    Error 17: GraphQLDocumentError: Unknown type "uuid".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/user-roles.graphql:6:43

    Error 18: GraphQLDocumentError: Unknown type "users".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/users.graphql:1:24

    Error 19: GraphQLDocumentError: Unknown type "uuid".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/users.graphql:26:17

    Error 20: GraphQLDocumentError: Cannot query field "user" on type "query_root".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/users.graphql:27:3

    Error 21: GraphQLDocumentError: Unknown type "users_bool_exp".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/users.graphql:32:21

    Error 22: GraphQLDocumentError: Cannot query field "users" on type "query_root".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/users.graphql:33:3

    Error 23: GraphQLDocumentError: Unknown type "uuid".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/users.graphql:39:18

    Error 24: GraphQLDocumentError: Unknown type "timestamptz".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/users.graphql:40:15

    Error 25: GraphQLDocumentError: Unknown type "uuid".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/users.graphql:61:48

    Error 26: GraphQLDocumentError: Cannot query field "authRefreshTokens" on type "query_root".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/users.graphql:62:3

    Error 27: GraphQLDocumentError: Unknown type "uuid".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/users.graphql:78:26

    Error 28: GraphQLDocumentError: Unknown type "users_set_input".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/users.graphql:78:40

    Error 29: GraphQLDocumentError: Unknown type "users_bool_exp".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/users.graphql:84:34

    Error 30: GraphQLDocumentError: Unknown type "users_set_input".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/users.graphql:84:58

    Error 31: GraphQLDocumentError: Unknown type "timestamptz".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/users.graphql:93:24

    Error 32: GraphQLDocumentError: Unknown type "citext".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/users.graphql:105:11

    Error 33: GraphQLDocumentError: Unknown type "timestamptz".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/users.graphql:107:9

    Error 34: GraphQLDocumentError: Unknown type "users_insert_input".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/users.graphql:126:28

    Error 35: GraphQLDocumentError: Unknown type "uuid".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/users.graphql:132:30

    Error 36: GraphQLDocumentError: Unknown type "uuid".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/users.graphql:142:35

    Error 37: GraphQLDocumentError: Unknown type "authUserProviders_insert_input".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/users.graphql:159:18

    Error 38: GraphQLDocumentError: Cannot query field "users" on type "query_root".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/users.graphql:167:3

    Error 39: GraphQLDocumentError: Unknown type "users_set_input".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/users.graphql:172:55
        at Object.checkValidationErrors (/Users/azlekov/Workspace/dodi/hasura-auth/node_modules/.pnpm/@graphql-tools+utils@8.6.2_graphql@16.2.0/node_modules/@graphql-tools/utils/
index.js:1253:15)
        at Object.codegen (/Users/azlekov/Workspace/dodi/hasura-auth/node_modules/.pnpm/@graphql-codegen+core@2.5.1_graphql@16.2.0/node_modules/@graphql-codegen/core/index.js:175
:15)
        at async process (/Users/azlekov/Workspace/dodi/hasura-auth/node_modules/.pnpm/@graphql-codegen+cli@2.6.2_saexda4meoafomkym5xogu2wwm/node_modules/@graphql-codegen/cli/bin
.js:1126:56)
        at async Promise.all (index 0)
        at async /Users/azlekov/Workspace/dodi/hasura-auth/node_modules/.pnpm/@graphql-codegen+cli@2.6.2_saexda4meoafomkym5xogu2wwm/node_modules/@graphql-codegen/cli/bin.js:1136:
37
        at async /Users/azlekov/Workspace/dodi/hasura-auth/node_modules/.pnpm/@graphql-codegen+cli@2.6.2_saexda4meoafomkym5xogu2wwm/node_modules/@graphql-codegen/cli/bin.js:925:2
1
    AggregateError: GraphQL Document Validation failed with 40 errors;
      Error 0: GraphQLDocumentError: Unknown type "users".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/provider-requests.graphql:1:24

    Error 1: GraphQLDocumentError: Unknown type "authProviderRequests_insert_input".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/provider-requests.graphql:2:21

    Error 2: GraphQLDocumentError: Unknown type "uuid".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/provider-requests.graphql:10:37

    Error 3: GraphQLDocumentError: Unknown type "uuid".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/provider-requests.graphql:17:28

    Error 4: GraphQLDocumentError: Cannot query field "authProviderRequest" on type "query_root".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/provider-requests.graphql:18:3

    Error 5: GraphQLDocumentError: Unknown type "users".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/refresh-tokens.graphql:1:24

    Error 6: GraphQLDocumentError: Unknown type "authRefreshTokens_insert_input".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/refresh-tokens.graphql:1:44

    Error 7: GraphQLDocumentError: Unknown type "uuid".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/refresh-tokens.graphql:7:44

    Error 8: GraphQLDocumentError: Unknown type "uuid".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/refresh-tokens.graphql:14:43

    Error 9: GraphQLDocumentError: Unknown type "users".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/user-providers.graphql:1:24

    Error 10: GraphQLDocumentError: Cannot query field "authUserProviders" on type "query_root".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/user-providers.graphql:2:3

    Error 11: GraphQLDocumentError: Unknown type "uuid".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/user-providers.graphql:18:29

    Error 12: GraphQLDocumentError: Cannot query field "authUserProviders" on type "query_root".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/user-providers.graphql:19:3

    Error 13: GraphQLDocumentError: Unknown type "uuid".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/user-providers.graphql:31:8

    Error 14: GraphQLDocumentError: Unknown type "authUserProviders_set_input".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/user-providers.graphql:32:22

    Error 15: GraphQLDocumentError: Unknown type "users".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/user-roles.graphql:1:24

    Error 16: GraphQLDocumentError: Unknown type "authUserRoles_insert_input".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/user-roles.graphql:1:39

    Error 17: GraphQLDocumentError: Unknown type "uuid".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/user-roles.graphql:6:43

    Error 18: GraphQLDocumentError: Unknown type "users".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/users.graphql:1:24

    Error 19: GraphQLDocumentError: Unknown type "uuid".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/users.graphql:26:17

    Error 20: GraphQLDocumentError: Cannot query field "user" on type "query_root".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/users.graphql:27:3

    Error 21: GraphQLDocumentError: Unknown type "users_bool_exp".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/users.graphql:32:21

    Error 22: GraphQLDocumentError: Cannot query field "users" on type "query_root".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/users.graphql:33:3

    Error 23: GraphQLDocumentError: Unknown type "uuid".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/users.graphql:39:18

    Error 24: GraphQLDocumentError: Unknown type "timestamptz".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/users.graphql:40:15

    Error 25: GraphQLDocumentError: Unknown type "uuid".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/users.graphql:61:48

    Error 26: GraphQLDocumentError: Cannot query field "authRefreshTokens" on type "query_root".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/users.graphql:62:3

    Error 27: GraphQLDocumentError: Unknown type "uuid".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/users.graphql:78:26

    Error 28: GraphQLDocumentError: Unknown type "users_set_input".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/users.graphql:78:40

    Error 29: GraphQLDocumentError: Unknown type "users_bool_exp".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/users.graphql:84:34

    Error 30: GraphQLDocumentError: Unknown type "users_set_input".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/users.graphql:84:58

    Error 31: GraphQLDocumentError: Unknown type "timestamptz".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/users.graphql:93:24

    Error 32: GraphQLDocumentError: Unknown type "citext".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/users.graphql:105:11

    Error 33: GraphQLDocumentError: Unknown type "timestamptz".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/users.graphql:107:9

    Error 34: GraphQLDocumentError: Unknown type "users_insert_input".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/users.graphql:126:28

    Error 35: GraphQLDocumentError: Unknown type "uuid".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/users.graphql:132:30

    Error 36: GraphQLDocumentError: Unknown type "uuid".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/users.graphql:142:35

    Error 37: GraphQLDocumentError: Unknown type "authUserProviders_insert_input".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/users.graphql:159:18

    Error 38: GraphQLDocumentError: Cannot query field "users" on type "query_root".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/users.graphql:167:3

    Error 39: GraphQLDocumentError: Unknown type "users_set_input".
        at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/users.graphql:172:55
        at Object.checkValidationErrors (/Users/azlekov/Workspace/dodi/hasura-auth/node_modules/.pnpm/@graphql-tools+utils@8.6.2_graphql@16.2.0/node_modules/@graphql-tools/utils/
index.js:1253:15)
        at Object.codegen (/Users/azlekov/Workspace/dodi/hasura-auth/node_modules/.pnpm/@graphql-codegen+core@2.5.1_graphql@16.2.0/node_modules/@graphql-codegen/core/index.js:175
:15)
        at async process (/Users/azlekov/Workspace/dodi/hasura-auth/node_modules/.pnpm/@graphql-codegen+cli@2.6.2_saexda4meoafomkym5xogu2wwm/node_modules/@graphql-codegen/cli/bin
.js:1126:56)
        at async Promise.all (index 0)
        at async /Users/azlekov/Workspace/dodi/hasura-auth/node_modules/.pnpm/@graphql-codegen+cli@2.6.2_saexda4meoafomkym5xogu2wwm/node_modules/@graphql-codegen/cli/bin.js:1136:
37
        at async /Users/azlekov/Workspace/dodi/hasura-auth/node_modules/.pnpm/@graphql-codegen+cli@2.6.2_saexda4meoafomkym5xogu2wwm/node_modules/@graphql-codegen/cli/bin.js:925:2
1


Something went wrong GraphQL Document Validation failed with 40 errors;
  Error 0: GraphQLDocumentError: Unknown type "users".
    at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/provider-requests.graphql:1:24

Error 1: GraphQLDocumentError: Unknown type "authProviderRequests_insert_input".
    at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/provider-requests.graphql:2:21

Error 2: GraphQLDocumentError: Unknown type "uuid".
    at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/provider-requests.graphql:10:37

Error 3: GraphQLDocumentError: Unknown type "uuid".
    at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/provider-requests.graphql:17:28

Error 4: GraphQLDocumentError: Cannot query field "authProviderRequest" on type "query_root".
    at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/provider-requests.graphql:18:3

Error 5: GraphQLDocumentError: Unknown type "users".
    at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/refresh-tokens.graphql:1:24

Error 6: GraphQLDocumentError: Unknown type "authRefreshTokens_insert_input".
    at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/refresh-tokens.graphql:1:44

Error 7: GraphQLDocumentError: Unknown type "uuid".
    at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/refresh-tokens.graphql:7:44

Error 8: GraphQLDocumentError: Unknown type "uuid".
    at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/refresh-tokens.graphql:14:43

Error 9: GraphQLDocumentError: Unknown type "users".
    at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/user-providers.graphql:1:24

Error 10: GraphQLDocumentError: Cannot query field "authUserProviders" on type "query_root".
    at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/user-providers.graphql:2:3

Error 11: GraphQLDocumentError: Unknown type "uuid".
    at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/user-providers.graphql:18:29

Error 12: GraphQLDocumentError: Cannot query field "authUserProviders" on type "query_root".
    at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/user-providers.graphql:19:3

Error 13: GraphQLDocumentError: Unknown type "uuid".
    at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/user-providers.graphql:31:8

Error 14: GraphQLDocumentError: Unknown type "authUserProviders_set_input".
    at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/user-providers.graphql:32:22

Error 15: GraphQLDocumentError: Unknown type "users".
    at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/user-roles.graphql:1:24

Error 16: GraphQLDocumentError: Unknown type "authUserRoles_insert_input".
    at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/user-roles.graphql:1:39

Error 17: GraphQLDocumentError: Unknown type "uuid".
    at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/user-roles.graphql:6:43

Error 18: GraphQLDocumentError: Unknown type "users".
    at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/users.graphql:1:24

Error 19: GraphQLDocumentError: Unknown type "uuid".
    at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/users.graphql:26:17

Error 20: GraphQLDocumentError: Cannot query field "user" on type "query_root".
    at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/users.graphql:27:3

Error 21: GraphQLDocumentError: Unknown type "users_bool_exp".
    at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/users.graphql:32:21

Error 22: GraphQLDocumentError: Cannot query field "users" on type "query_root".
    at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/users.graphql:33:3

Error 23: GraphQLDocumentError: Unknown type "uuid".
    at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/users.graphql:39:18

Error 24: GraphQLDocumentError: Unknown type "timestamptz".
    at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/users.graphql:40:15

Error 25: GraphQLDocumentError: Unknown type "uuid".
    at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/users.graphql:61:48

Error 26: GraphQLDocumentError: Cannot query field "authRefreshTokens" on type "query_root".
    at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/users.graphql:62:3

Error 27: GraphQLDocumentError: Unknown type "uuid".
    at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/users.graphql:78:26

Error 28: GraphQLDocumentError: Unknown type "users_set_input".
    at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/users.graphql:78:40

Error 29: GraphQLDocumentError: Unknown type "users_bool_exp".
    at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/users.graphql:84:34

Error 30: GraphQLDocumentError: Unknown type "users_set_input".
    at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/users.graphql:84:58

Error 31: GraphQLDocumentError: Unknown type "timestamptz".
    at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/users.graphql:93:24

Error 32: GraphQLDocumentError: Unknown type "citext".
    at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/users.graphql:105:11

Error 33: GraphQLDocumentError: Unknown type "timestamptz".
    at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/users.graphql:107:9

Error 34: GraphQLDocumentError: Unknown type "users_insert_input".
    at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/users.graphql:126:28

Error 35: GraphQLDocumentError: Unknown type "uuid".
    at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/users.graphql:132:30

Error 36: GraphQLDocumentError: Unknown type "uuid".
    at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/users.graphql:142:35

Error 37: GraphQLDocumentError: Unknown type "authUserProviders_insert_input".
    at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/users.graphql:159:18

Error 38: GraphQLDocumentError: Cannot query field "users" on type "query_root".
    at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/users.graphql:167:3

Error 39: GraphQLDocumentError: Unknown type "users_set_input".
    at /Users/azlekov/Workspace/dodi/hasura-auth/src/gql/users.graphql:172:55
 ELIFECYCLE  Command failed with exit code 1.
ERROR: "codegen:watch" exited with 1.
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by djedi** [comment]
Ditto. Thanks for the tip!

**Comment by elitan** [comment]
I'm on pnpm v 7.1.0 and things are working for me. Let me know if this is still an issue and I'll reopen the issue.
