### ISSUE TITLE
Applying migrations... fail

### ISSUE THREAD

**Issue by chanthavong** [nhost/hasura-auth#163]
first run docker composee [nhost/hasura-auth] (help me 🙏 😅)

error code

```base
{"level":30,"time":1652923504251,"pid":18,"hostname":"09699a726a8e","msg":"Log level: info"}
hasura-auth_1  | {"level":30,"time":1652923504716,"pid":18,"hostname":"09699a726a8e","msg":"Waiting for Hasura to be ready..."}
hasura-auth_1  | {"level":30,"time":1652923504929,"pid":18,"hostname":"09699a726a8e","msg":"Hasura is ready"}
hasura-auth_1  | {"level":30,"time":1652923504929,"pid":18,"hostname":"09699a726a8e","msg":"Applying migrations..."}
hasura-auth_1  | (node:18) UnhandledPromiseRejectionWarning: Error: certificate has expired
hasura-auth_1  |     at applyMigrations (/app/dist/migrations.js:62:19)
hasura-auth_1  |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
hasura-auth_1  |     at async start (/app/dist/server.js:43:5)
hasura-auth_1  | (Use `node --trace-warnings ...` to show where the warning was created)
hasura-auth_1  | (node:18) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
hasura-auth_1  | (node:18) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by elitan** [comment]
Could the error "certificate has expired" be related to Postgres and any certificate you might have there?
