### ISSUE TITLE
Sign in through Social Login LinkedIn throws 500 error

### ISSUE THREAD

**Issue by alveshelio** [nhost/hasura-auth#175]
This is happening in local but also in production sometimes, it's harder to reproduce in production though
![image](https://user-images.githubusercontent.com/8176422/171021365-7b305dc5-ea87-498c-9656-f152d29937d3.png)

I need to go back to the site try to login again and then it works.

**Comment by elitan** [comment]
What error do you get in the server logs when this happens locally?

```
docker logs -f nhost-auth
```

**Comment by plmercereau** [comment]
What could also help is the full URL in your browser tab

**Comment by alveshelio** [comment]
After upgrading to the latest version of @nhost/nextjs and @nhost/react I no longer have this issue.

**Comment by alveshelio** [comment]
Hi @elitan  I though it had been fixed but I'm getting it again.

Here are the logs I'm getting on localhost:
```json
{
  "level": 30,
  "time": 1654260668400,
  "pid": 18,
  "hostname": "76c3cf7c8694",
  "req": {
    "id": 3,
    "method": "GET",
    "url": "/signin/provider/linkedin?redirectTo=http%3A%2F%2Flocalhost%3A3000%2F&locale=en",
    "query": {
      "redirectTo": "http://localhost:3000/",
      "locale": "en"
    },
    "params": {},
    "headers": {
      "host": "localhost:1337",
      "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36",
      "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
      "accept-encoding": "gzip, deflate, br",
      "accept-language": "en-US,en;q=0.9,fr-CA;q=0.8,fr;q=0.7",
      "cookie": "chakra-ui-color-mode=dark; cc_cookie={\"level\":[\"necessary\"],\"revision\":0,\"data\":null,\"rfc_cookie\":false}; L=en-ca",
      "referer": "http://localhost:3000/",
      "sec-fetch-dest": "document",
      "sec-fetch-mode": "navigate",
      "sec-fetch-site": "same-site",
      "sec-fetch-user": "?1",
      "sec-gpc": "1",
      "upgrade-insecure-requests": "1",
      "x-forwarded-for": "::1"
    },
    "remoteAddress": "::ffff:172.17.0.1",
    "remotePort": 63906
  },
  "res": {
    "statusCode": 302,
    "headers": {
      "x-dns-prefetch-control": "off",
      "x-frame-options": "SAMEORIGIN",
      "strict-transport-security": "max-age=15552000; includeSubDomains",
      "x-download-options": "noopen",
      "x-content-type-options": "nosniff",
      "x-xss-protection": "1; mode=block",
      "access-control-allow-origin": "*",
      "surrogate-control": "no-store",
      "cache-control": "no-store, no-cache, must-revalidate, proxy-revalidate",
      "pragma": "no-cache",
      "expires": "0",
      "location": "https://www.linkedin.com/oauth/v2/authorization?state=7342e442-51eb-48a7-8a80-4a3d367c859d&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A1337%2Fv1%2Fauth%2Fsignin%2Fprovider%2Flinkedin%2Fcallback&scope=r_emailaddress%20r_liteprofile&client_id=77yr0n3w084nwc",
      "content-length": "0"
    }
  },
  "responseTime": 24,
  "msg": "request completed"
}
{
  "level": 50,
  "time": 1654260673464,
  "pid": 18,
  "hostname": "76c3cf7c8694",
  "msg": "Cannot read property 'redirectTo' of undefined"
}
{
  "level": 30,
  "time": 1654260673464,
  "pid": 18,
  "hostname": "76c3cf7c8694",
  "req": {
    "id": 5,
    "method": "GET",
    "url": "/signin/provider/linkedin/callback?code=AQQbqtlt34SGvZY3jozuLSMcuCQwPlZubx9_9xZVM66kaLAvS5sVYLDwkZh8QrYuSQDDiWsyci2SDCDfRIJ144nLIKugN594vOFpOHeix15315JYYc5JbqJognnmHLxSFhIsUpMzBnH23yZQsN6Md6HM9ZxqGs28ECAnlpgkiamzYoHzY20mESM9RWJJAL2nHcSyhohxaJOYJDN_hs8&state=7342e442-51eb-48a7-8a80-4a3d367c859d",
    "query": {
      "code": "AQQbqtlt34SGvZY3jozuLSMcuCQwPlZubx9_9xZVM66kaLAvS5sVYLDwkZh8QrYuSQDDiWsyci2SDCDfRIJ144nLIKugN594vOFpOHeix15315JYYc5JbqJognnmHLxSFhIsUpMzBnH23yZQsN6Md6HM9ZxqGs28ECAnlpgkiamzYoHzY20mESM9RWJJAL2nHcSyhohxaJOYJDN_hs8",
      "state": "7342e442-51eb-48a7-8a80-4a3d367c859d"
    },
    "params": {},
    "headers": {
      "host": "localhost:1337",
      "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36",
      "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
      "accept-encoding": "gzip, deflate, br",
      "accept-language": "en-US,en;q=0.9,fr-CA;q=0.8,fr;q=0.7",
      "cache-control": "max-age=0",
      "cookie": "chakra-ui-color-mode=dark; cc_cookie={\"level\":[\"necessary\"],\"revision\":0,\"data\":null,\"rfc_cookie\":false}; L=en-ca",
      "sec-fetch-dest": "document",
      "sec-fetch-mode": "navigate",
      "sec-fetch-site": "cross-site",
      "sec-fetch-user": "?1",
      "sec-gpc": "1",
      "upgrade-insecure-requests": "1",
      "x-forwarded-for": "::1"
    },
    "remoteAddress": "::ffff:172.17.0.1",
    "remotePort": 63926
  },
  "res": {
    "statusCode": 500,
    "headers": {
      "x-dns-prefetch-control": "off",
      "x-frame-options": "SAMEORIGIN",
      "strict-transport-security": "max-age=15552000; includeSubDomains",
      "x-download-options": "noopen",
      "x-content-type-options": "nosniff",
      "x-xss-protection": "1; mode=block",
      "access-control-allow-origin": "*",
      "surrogate-control": "no-store",
      "cache-control": "no-store, no-cache, must-revalidate, proxy-revalidate",
      "pragma": "no-cache",
      "expires": "0"
    }
  },
  "err": {
    "type": "Error",
    "message": "failed with status code 500",
    "stack": "Error: failed with status code 500\n    at ServerResponse.onResFinished (/app/node_modules/.pnpm/pino-http@5.8.0/node_modules/pino-http/logger.js:77:38)\n    at ServerResponse.emit (events.js:412:35)\n    at onFinish (_http_outgoing.js:792:10)\n    at afterWrite (internal/streams/writable.js:466:5)\n    at afterWriteTick (internal/streams/writable.js:453:10)\n    at processTicksAndRejections (internal/process/task_queues.js:81:21)"
  },
  "responseTime": 868,
  "msg": "request errored"
}
```
What I find particularly strange is this log
```json
{
  "level": 50,
  "time": 1654260673464,
  "pid": 18,
  "hostname": "76c3cf7c8694",
  "msg": "Cannot read property 'redirectTo' of undefined"
}
```
Because I'm sending this object to options
```ts
{
  "redirectTo": "/",
  "locale": "en"
}
```
What's even stranger is that when I go back to the site and I try to sign in again and this time it works fine. I don't know if it's because I'm already signed in in LinkedIn or not, I'm not asked the to sign in in LinkedIn anymore, but it just goes through and I get signed in.

**Comment by elitan** [comment]
This issue has been fixed.
