### ISSUE TITLE
Fatal Error:- Environment variable HASURA_GRAPHQL_JWT_SECRET

### ISSUE THREAD

**Issue by lnorton89** [nhost/hasura-auth#299]
When bringing up the stack following the instructions and example .env file I get this error. 

```sh
hasura-auth_1     | SyntaxError: Unexpected token ' in JSON at position 0
hasura-auth_1     |     at JSON.parse (<anonymous>)
hasura-auth_1     |     at castObjectEnv (/app/dist/config/utils.js:29:23)
hasura-auth_1     |     at Object.get HASURA_GRAPHQL_JWT_SECRET [as HASURA_GRAPHQL_JWT_SECRET] (/app/dist/utils/env.js:12:42)
hasura-auth_1     |     at Object.<anonymous> (/app/dist/utils/jwt/get-claims.js:8:43)
hasura-auth_1     |     at Module._compile (node:internal/modules/cjs/loader:1155:14)
hasura-auth_1     |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
hasura-auth_1     |     at Module.load (node:internal/modules/cjs/loader:1033:32)
hasura-auth_1     |     at Function.Module._load (node:internal/modules/cjs/loader:868:12)
hasura-auth_1     |     at Module.require (node:internal/modules/cjs/loader:1057:19)
hasura-auth_1     |     at require (node:internal/modules/cjs/helpers:103:18)
hasura-auth_1     |     at Object.<anonymous> (/app/dist/utils/jwt/index.js:14:14)
hasura-auth_1     |     at Module._compile (node:internal/modules/cjs/loader:1155:14)
hasura-auth_1     |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
hasura-auth_1     |     at Module.load (node:internal/modules/cjs/loader:1033:32)
hasura-auth_1     |     at Function.Module._load (node:internal/modules/cjs/loader:868:12)
hasura-auth_1     |     at Module.require (node:internal/modules/cjs/loader:1057:19)
hasura-auth_1     |  ELIFECYCLE  Command failed with exit code 1.
hasura-auth_hasura-auth_1 exited with code 1
graphql-engine_1  | Fatal Error:- Environment variable HASURA_GRAPHQL_JWT_SECRET: Error in $: Failed reading: not a valid json value
```

```
HASURA_GRAPHQL_JWT_SECRET='{"type":"HS256", "key":"5152fa850c02dc222631cca898ed1485821a70912a6e3649c49076912daa3b62182ba013315915d64f40cddfbb8b58eb5bd11ba225336a6af45bbae07ca873f3","issuer":"hasura-auth"}'
````

```
Linux myhostname 5.10.0-19-amd64 #1 SMP Debian 5.10.149-2 (2022-10-21) x86_64
docker-ce is already the newest version (5:20.10.21~3-0~debian-bullseye)
```

**Comment by lnorton89** [comment]
Closed with submitted PR to solve issue (#300)
