### ISSUE TITLE
container fails to start due to failed migrations called

### ISSUE THREAD

**Issue by fracet** [nhost/hasura-auth#42]
Hi
I installed the latest hasura-auth docker image and I am getting the following error when it starts:

`2021-11-18T17:36:13.215063196Z yarn run v1.22.15
2021-11-18T17:36:13.310451921Z $ node -r ./dist/start.js
2021-11-18T17:36:16.010300921Z {"level":30,"time":1637256976007,"pid":29,"hostname":"f89ed166a3bd","msg":"Hasura is ready"}
2021-11-18T17:36:16.090766635Z (node:29) UnhandledPromiseRejectionWarning: Error: Migration failed. Reason: An error occurred running 'create-initial-tables'. Rolled back this migration. No further migrations were run. Reason: function "set_current_timestamp_updated_at" already exists with same argument types
2021-11-18T17:36:16.090800706Z     at /app/node_modules/@djgrant/postgres-migrations/dist/migrate.js:63:27
2021-11-18T17:36:16.090806676Z     at processTicksAndRejections (internal/process/task_queues.js:95:5)
2021-11-18T17:36:16.090811016Z     at async /app/node_modules/@djgrant/postgres-migrations/dist/with-lock.js:24:28
2021-11-18T17:36:16.090815196Z     at async Object.applyMigrations (/app/dist/migrations.js:16:9)
2021-11-18T17:36:16.090819126Z     at async start (/app/dist/ts-start.js:42:5)
2021-11-18T17:36:16.090822686Z (Use `node --trace-warnings ...` to show where the warning was created)
2021-11-18T17:36:16.090826926Z (node:29) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
2021-11-18T17:36:16.090833916Z (node:29) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2021-11-18T17:36:16.136545350Z Done in 2.93s.
`
this keeps going on and on in a restart loop.

I have also set the following env variables:

HASURA_GRAPHQL_DATABASE_URL=postgres://ourPGDB
HASURA_GRAPHQL_JWT_SECRET={ "type": "HS256", "key": "ourkey"}
HASURA_GRAPHQL_ADMIN_SECRET=oursecret
HASURA_GRAPHQL_GRAPHQL_URL=http://srv-captain--hasura-graphql-engine:8080/v1/graphql

(the hasura installation itself works fine, so the details above are correct)

I had installed the migrations SQL manually before (so all the tables in auth are already there), but I would expect the script to notice that and move on.

**Comment by elitan** [comment]
@fracet Is this still an issue? We've not seen this in production nor locally when developing.

I'll close this for now but I'm happy to re-open if necessary.
